version: "3.9"
services:
    node:
        image: node:12-alpine
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: sqs-utilities
        env_file: .env
        environment:
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - AWS_REGION=$AWS_REGION
            - QUEUE_URL=$QUEUE_URL
            - ENTRIES=$ENTRIES
        volumes:
            - .:/src
        command: npm start
